include(":app")
include(":shared")
include(":summer")
include(":summer-androidx")
include(":summer-android-save-state")
include(":summer-serialization-strategy")
include(":summer_android_serialization_save_state")
include(":summer-android-support")