source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosApp
  pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git'
  pod 'AlamofireImage', :git => 'https://github.com/Alamofire/AlamofireImage.git'

  target 'iosAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'shared' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for shared

end
