source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'SummerStoryboard' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SummerStoryboard
  pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git'
  pod 'AlamofireImage', :git => 'https://github.com/Alamofire/AlamofireImage.git'

  pod 'shared', path: '../shared'

  target 'SummerStoryboardTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
