package summer.events

import summer.GetViewProvider
import kotlin.jvm.JvmField

/**
 * Proxy that calls action following defined [EventProxyStrategy].
 * Can proxy actions with 0-12 arguments. Have child to each supported arity.
 *
 * Implementations are generated by SummerEventGenerator.kts
 */
abstract class EventProxy<TView, in TOwner> {

    abstract val strategy: EventProxyStrategy<TView, TOwner>
    abstract fun viewCreated()

    interface ViewEventExecutor<TView> {
        fun execute(view: TView)
    }

    class A0<TView, in TOwner>(
        private val getViewEvent: (TView) -> (() -> Unit),
        private val owner: TOwner,
        private val getViewProvider: GetViewProvider<TView>,
        private val listener: EventProxyListener<TView, TOwner>?,
        override val strategy: EventProxyStrategy<TView, TOwner>,
    ) : () -> Unit, EventProxy<TView, TOwner>() {

        override fun viewCreated() {
            strategy.viewCreated(owner, getViewProvider)
        }

        override fun invoke() {
            val executor = EventExecutor()
            strategy.proxyInvoked(executor, owner, getViewProvider)
            listener?.proxyInvoked(strategy, executor, owner)
        }

        @Suppress("MemberVisibilityCanBePrivate")
        inner class EventExecutor : ViewEventExecutor<TView> {

            override fun execute(view: TView) {
                val viewEvent = getViewEvent(view)
                viewEvent()
                listener?.viewEventExecuted(view, strategy, viewEventExecutor = this, owner)
            }
        }
    }

    class A1<TView, in TOwner, T1>(
        private val getViewEvent: (TView) -> ((T1) -> Unit),
        private val owner: TOwner,
        private val getViewProvider: GetViewProvider<TView>,
        private val listener: EventProxyListener<TView, TOwner>?,
        override val strategy: EventProxyStrategy<TView, TOwner>,
    ) : (T1) -> Unit, EventProxy<TView, TOwner>() {

        override fun viewCreated() {
            strategy.viewCreated(owner, getViewProvider)
        }

        override fun invoke(p1: T1) {
            val executor = EventExecutor(p1)
            strategy.proxyInvoked(executor, owner, getViewProvider)
            listener?.proxyInvoked(strategy, executor, owner)
        }

        @Suppress("MemberVisibilityCanBePrivate")
        inner class EventExecutor(@JvmField val p1: T1) : ViewEventExecutor<TView> {

            override fun execute(view: TView) {
                val viewEvent = getViewEvent(view)
                viewEvent(p1)
                listener?.viewEventExecuted(view, strategy, viewEventExecutor = this, owner)
            }
        }
    }

    class A2<TView, in TOwner, T1, T2>(
        private val getViewEvent: (TView) -> ((T1, T2) -> Unit),
        private val owner: TOwner,
        private val getViewProvider: GetViewProvider<TView>,
        private val listener: EventProxyListener<TView, TOwner>?,
        override val strategy: EventProxyStrategy<TView, TOwner>,
    ) : (T1, T2) -> Unit, EventProxy<TView, TOwner>() {

        override fun viewCreated() {
            strategy.viewCreated(owner, getViewProvider)
        }

        override fun invoke(p1: T1, p2: T2) {
            val executor = EventExecutor(p1, p2)
            strategy.proxyInvoked(executor, owner, getViewProvider)
            listener?.proxyInvoked(strategy, executor, owner)
        }

        @Suppress("MemberVisibilityCanBePrivate")
        inner class EventExecutor(@JvmField val p1: T1, @JvmField val p2: T2) : ViewEventExecutor<TView> {

            override fun execute(view: TView) {
                val viewEvent = getViewEvent(view)
                viewEvent(p1, p2)
                listener?.viewEventExecuted(view, strategy, viewEventExecutor = this, owner)
            }
        }
    }

    class A3<TView, in TOwner, T1, T2, T3>(
        private val getViewEvent: (TView) -> ((T1, T2, T3) -> Unit),
        private val owner: TOwner,
        private val getViewProvider: GetViewProvider<TView>,
        private val listener: EventProxyListener<TView, TOwner>?,
        override val strategy: EventProxyStrategy<TView, TOwner>,
    ) : (T1, T2, T3) -> Unit, EventProxy<TView, TOwner>() {

        override fun viewCreated() {
            strategy.viewCreated(owner, getViewProvider)
        }

        override fun invoke(p1: T1, p2: T2, p3: T3) {
            val executor = EventExecutor(p1, p2, p3)
            strategy.proxyInvoked(executor, owner, getViewProvider)
            listener?.proxyInvoked(strategy, executor, owner)
        }

        @Suppress("MemberVisibilityCanBePrivate")
        inner class EventExecutor(@JvmField val p1: T1, @JvmField val p2: T2, @JvmField val p3: T3) : ViewEventExecutor<TView> {

            override fun execute(view: TView) {
                val viewEvent = getViewEvent(view)
                viewEvent(p1, p2, p3)
                listener?.viewEventExecuted(view, strategy, viewEventExecutor = this, owner)
            }
        }
    }

    class A4<TView, in TOwner, T1, T2, T3, T4>(
        private val getViewEvent: (TView) -> ((T1, T2, T3, T4) -> Unit),
        private val owner: TOwner,
        private val getViewProvider: GetViewProvider<TView>,
        private val listener: EventProxyListener<TView, TOwner>?,
        override val strategy: EventProxyStrategy<TView, TOwner>,
    ) : (T1, T2, T3, T4) -> Unit, EventProxy<TView, TOwner>() {

        override fun viewCreated() {
            strategy.viewCreated(owner, getViewProvider)
        }

        override fun invoke(p1: T1, p2: T2, p3: T3, p4: T4) {
            val executor = EventExecutor(p1, p2, p3, p4)
            strategy.proxyInvoked(executor, owner, getViewProvider)
            listener?.proxyInvoked(strategy, executor, owner)
        }

        @Suppress("MemberVisibilityCanBePrivate")
        inner class EventExecutor(@JvmField val p1: T1, @JvmField val p2: T2, @JvmField val p3: T3, @JvmField val p4: T4) : ViewEventExecutor<TView> {

            override fun execute(view: TView) {
                val viewEvent = getViewEvent(view)
                viewEvent(p1, p2, p3, p4)
                listener?.viewEventExecuted(view, strategy, viewEventExecutor = this, owner)
            }
        }
    }

    class A5<TView, in TOwner, T1, T2, T3, T4, T5>(
        private val getViewEvent: (TView) -> ((T1, T2, T3, T4, T5) -> Unit),
        private val owner: TOwner,
        private val getViewProvider: GetViewProvider<TView>,
        private val listener: EventProxyListener<TView, TOwner>?,
        override val strategy: EventProxyStrategy<TView, TOwner>,
    ) : (T1, T2, T3, T4, T5) -> Unit, EventProxy<TView, TOwner>() {

        override fun viewCreated() {
            strategy.viewCreated(owner, getViewProvider)
        }

        override fun invoke(p1: T1, p2: T2, p3: T3, p4: T4, p5: T5) {
            val executor = EventExecutor(p1, p2, p3, p4, p5)
            strategy.proxyInvoked(executor, owner, getViewProvider)
            listener?.proxyInvoked(strategy, executor, owner)
        }

        @Suppress("MemberVisibilityCanBePrivate")
        inner class EventExecutor(@JvmField val p1: T1, @JvmField val p2: T2, @JvmField val p3: T3, @JvmField val p4: T4, @JvmField val p5: T5) : ViewEventExecutor<TView> {

            override fun execute(view: TView) {
                val viewEvent = getViewEvent(view)
                viewEvent(p1, p2, p3, p4, p5)
                listener?.viewEventExecuted(view, strategy, viewEventExecutor = this, owner)
            }
        }
    }

    class A6<TView, in TOwner, T1, T2, T3, T4, T5, T6>(
        private val getViewEvent: (TView) -> ((T1, T2, T3, T4, T5, T6) -> Unit),
        private val owner: TOwner,
        private val getViewProvider: GetViewProvider<TView>,
        private val listener: EventProxyListener<TView, TOwner>?,
        override val strategy: EventProxyStrategy<TView, TOwner>,
    ) : (T1, T2, T3, T4, T5, T6) -> Unit, EventProxy<TView, TOwner>() {

        override fun viewCreated() {
            strategy.viewCreated(owner, getViewProvider)
        }

        override fun invoke(p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, p6: T6) {
            val executor = EventExecutor(p1, p2, p3, p4, p5, p6)
            strategy.proxyInvoked(executor, owner, getViewProvider)
            listener?.proxyInvoked(strategy, executor, owner)
        }

        @Suppress("MemberVisibilityCanBePrivate")
        inner class EventExecutor(@JvmField val p1: T1, @JvmField val p2: T2, @JvmField val p3: T3, @JvmField val p4: T4, @JvmField val p5: T5, @JvmField val p6: T6) : ViewEventExecutor<TView> {

            override fun execute(view: TView) {
                val viewEvent = getViewEvent(view)
                viewEvent(p1, p2, p3, p4, p5, p6)
                listener?.viewEventExecuted(view, strategy, viewEventExecutor = this, owner)
            }
        }
    }

    class A7<TView, in TOwner, T1, T2, T3, T4, T5, T6, T7>(
        private val getViewEvent: (TView) -> ((T1, T2, T3, T4, T5, T6, T7) -> Unit),
        private val owner: TOwner,
        private val getViewProvider: GetViewProvider<TView>,
        private val listener: EventProxyListener<TView, TOwner>?,
        override val strategy: EventProxyStrategy<TView, TOwner>,
    ) : (T1, T2, T3, T4, T5, T6, T7) -> Unit, EventProxy<TView, TOwner>() {

        override fun viewCreated() {
            strategy.viewCreated(owner, getViewProvider)
        }

        override fun invoke(p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, p6: T6, p7: T7) {
            val executor = EventExecutor(p1, p2, p3, p4, p5, p6, p7)
            strategy.proxyInvoked(executor, owner, getViewProvider)
            listener?.proxyInvoked(strategy, executor, owner)
        }

        @Suppress("MemberVisibilityCanBePrivate")
        inner class EventExecutor(@JvmField val p1: T1, @JvmField val p2: T2, @JvmField val p3: T3, @JvmField val p4: T4, @JvmField val p5: T5, @JvmField val p6: T6, @JvmField val p7: T7) : ViewEventExecutor<TView> {

            override fun execute(view: TView) {
                val viewEvent = getViewEvent(view)
                viewEvent(p1, p2, p3, p4, p5, p6, p7)
                listener?.viewEventExecuted(view, strategy, viewEventExecutor = this, owner)
            }
        }
    }

    class A8<TView, in TOwner, T1, T2, T3, T4, T5, T6, T7, T8>(
        private val getViewEvent: (TView) -> ((T1, T2, T3, T4, T5, T6, T7, T8) -> Unit),
        private val owner: TOwner,
        private val getViewProvider: GetViewProvider<TView>,
        private val listener: EventProxyListener<TView, TOwner>?,
        override val strategy: EventProxyStrategy<TView, TOwner>,
    ) : (T1, T2, T3, T4, T5, T6, T7, T8) -> Unit, EventProxy<TView, TOwner>() {

        override fun viewCreated() {
            strategy.viewCreated(owner, getViewProvider)
        }

        override fun invoke(p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, p6: T6, p7: T7, p8: T8) {
            val executor = EventExecutor(p1, p2, p3, p4, p5, p6, p7, p8)
            strategy.proxyInvoked(executor, owner, getViewProvider)
            listener?.proxyInvoked(strategy, executor, owner)
        }

        @Suppress("MemberVisibilityCanBePrivate")
        inner class EventExecutor(@JvmField val p1: T1, @JvmField val p2: T2, @JvmField val p3: T3, @JvmField val p4: T4, @JvmField val p5: T5, @JvmField val p6: T6, @JvmField val p7: T7, @JvmField val p8: T8) : ViewEventExecutor<TView> {

            override fun execute(view: TView) {
                val viewEvent = getViewEvent(view)
                viewEvent(p1, p2, p3, p4, p5, p6, p7, p8)
                listener?.viewEventExecuted(view, strategy, viewEventExecutor = this, owner)
            }
        }
    }

    class A9<TView, in TOwner, T1, T2, T3, T4, T5, T6, T7, T8, T9>(
        private val getViewEvent: (TView) -> ((T1, T2, T3, T4, T5, T6, T7, T8, T9) -> Unit),
        private val owner: TOwner,
        private val getViewProvider: GetViewProvider<TView>,
        private val listener: EventProxyListener<TView, TOwner>?,
        override val strategy: EventProxyStrategy<TView, TOwner>,
    ) : (T1, T2, T3, T4, T5, T6, T7, T8, T9) -> Unit, EventProxy<TView, TOwner>() {

        override fun viewCreated() {
            strategy.viewCreated(owner, getViewProvider)
        }

        override fun invoke(p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, p6: T6, p7: T7, p8: T8, p9: T9) {
            val executor = EventExecutor(p1, p2, p3, p4, p5, p6, p7, p8, p9)
            strategy.proxyInvoked(executor, owner, getViewProvider)
            listener?.proxyInvoked(strategy, executor, owner)
        }

        @Suppress("MemberVisibilityCanBePrivate")
        inner class EventExecutor(@JvmField val p1: T1, @JvmField val p2: T2, @JvmField val p3: T3, @JvmField val p4: T4, @JvmField val p5: T5, @JvmField val p6: T6, @JvmField val p7: T7, @JvmField val p8: T8, @JvmField val p9: T9) : ViewEventExecutor<TView> {

            override fun execute(view: TView) {
                val viewEvent = getViewEvent(view)
                viewEvent(p1, p2, p3, p4, p5, p6, p7, p8, p9)
                listener?.viewEventExecuted(view, strategy, viewEventExecutor = this, owner)
            }
        }
    }

    class A10<TView, in TOwner, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(
        private val getViewEvent: (TView) -> ((T1, T2, T3, T4, T5, T6, T7, T8, T9, T10) -> Unit),
        private val owner: TOwner,
        private val getViewProvider: GetViewProvider<TView>,
        private val listener: EventProxyListener<TView, TOwner>?,
        override val strategy: EventProxyStrategy<TView, TOwner>,
    ) : (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10) -> Unit, EventProxy<TView, TOwner>() {

        override fun viewCreated() {
            strategy.viewCreated(owner, getViewProvider)
        }

        override fun invoke(p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, p6: T6, p7: T7, p8: T8, p9: T9, p10: T10) {
            val executor = EventExecutor(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10)
            strategy.proxyInvoked(executor, owner, getViewProvider)
            listener?.proxyInvoked(strategy, executor, owner)
        }

        @Suppress("MemberVisibilityCanBePrivate")
        inner class EventExecutor(@JvmField val p1: T1, @JvmField val p2: T2, @JvmField val p3: T3, @JvmField val p4: T4, @JvmField val p5: T5, @JvmField val p6: T6, @JvmField val p7: T7, @JvmField val p8: T8, @JvmField val p9: T9, @JvmField val p10: T10) : ViewEventExecutor<TView> {

            override fun execute(view: TView) {
                val viewEvent = getViewEvent(view)
                viewEvent(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10)
                listener?.viewEventExecuted(view, strategy, viewEventExecutor = this, owner)
            }
        }
    }

    class A11<TView, in TOwner, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>(
        private val getViewEvent: (TView) -> ((T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11) -> Unit),
        private val owner: TOwner,
        private val getViewProvider: GetViewProvider<TView>,
        private val listener: EventProxyListener<TView, TOwner>?,
        override val strategy: EventProxyStrategy<TView, TOwner>,
    ) : (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11) -> Unit, EventProxy<TView, TOwner>() {

        override fun viewCreated() {
            strategy.viewCreated(owner, getViewProvider)
        }

        override fun invoke(p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, p6: T6, p7: T7, p8: T8, p9: T9, p10: T10, p11: T11) {
            val executor = EventExecutor(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11)
            strategy.proxyInvoked(executor, owner, getViewProvider)
            listener?.proxyInvoked(strategy, executor, owner)
        }

        @Suppress("MemberVisibilityCanBePrivate")
        inner class EventExecutor(@JvmField val p1: T1, @JvmField val p2: T2, @JvmField val p3: T3, @JvmField val p4: T4, @JvmField val p5: T5, @JvmField val p6: T6, @JvmField val p7: T7, @JvmField val p8: T8, @JvmField val p9: T9, @JvmField val p10: T10, @JvmField val p11: T11) : ViewEventExecutor<TView> {

            override fun execute(view: TView) {
                val viewEvent = getViewEvent(view)
                viewEvent(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11)
                listener?.viewEventExecuted(view, strategy, viewEventExecutor = this, owner)
            }
        }
    }

    class A12<TView, in TOwner, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>(
        private val getViewEvent: (TView) -> ((T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12) -> Unit),
        private val owner: TOwner,
        private val getViewProvider: GetViewProvider<TView>,
        private val listener: EventProxyListener<TView, TOwner>?,
        override val strategy: EventProxyStrategy<TView, TOwner>,
    ) : (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12) -> Unit, EventProxy<TView, TOwner>() {

        override fun viewCreated() {
            strategy.viewCreated(owner, getViewProvider)
        }

        override fun invoke(p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, p6: T6, p7: T7, p8: T8, p9: T9, p10: T10, p11: T11, p12: T12) {
            val executor = EventExecutor(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12)
            strategy.proxyInvoked(executor, owner, getViewProvider)
            listener?.proxyInvoked(strategy, executor, owner)
        }

        @Suppress("MemberVisibilityCanBePrivate")
        inner class EventExecutor(@JvmField val p1: T1, @JvmField val p2: T2, @JvmField val p3: T3, @JvmField val p4: T4, @JvmField val p5: T5, @JvmField val p6: T6, @JvmField val p7: T7, @JvmField val p8: T8, @JvmField val p9: T9, @JvmField val p10: T10, @JvmField val p11: T11, @JvmField val p12: T12) : ViewEventExecutor<TView> {

            override fun execute(view: TView) {
                val viewEvent = getViewEvent(view)
                viewEvent(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12)
                listener?.viewEventExecuted(view, strategy, viewEventExecutor = this, owner)
            }
        }
    }
}

